language: python
sudo: false
cache:
  directories:
  - ~/virtualenv
python:
- '2.7'
- '3.3'
- pypy
install:
- wget public-travis-scripts.polysquare.org/python-install.sh
- wget public-travis-scripts.polysquare.org/python-lint.sh
- wget public-travis-scripts.polysquare.org/python-tests.sh
- wget public-travis-scripts.polysquare.org/python-coverage.sh
- wget public-travis-scripts.polysquare.org/project-lint.sh
- wget public-travis-scripts.polysquare.org/setup-lang.sh
- wget public-travis-scripts.polysquare.org/prepare-lang-cache.sh
- source setup-lang.sh -l haskell -p ~/virtualenv/haskell
- bash python-install.sh -p
script:
- echo "${TRAVIS_PYTHON_VERSION}"
- bash project-lint.sh -d . -e py
- bash python-lint.sh -m polysquarelinter
- bash python-tests.sh -m polysquarelinter
- bash prepare-lang-cache.sh -p ~/virtualenv/haskell -l haskell
after_success:
- bash python-coverage.sh
deploy:
  provider: pypi
  user:
    secure: CtbbLFM7+9o+skLwdzjBsU7S7LbmmCfiZs947+CSFqs+kkAzTghIGllYHZHmd6W2FKjM7E3hiBvGrgkSRIJzygjwvEfXbp8kwFdpOyWVj3wy7/FpERxha4nWRfnU0/pyJJyIEPdo55YVqd72VU0grqu6BDfCXTKacTzD8ZSV58U=
  password:
    secure: ZnhModnrfduaNAor01dfPy+y/46fY35DkNuLEeJxEGaXZE12TFLLd1OLwZ/9SJsSKKq2NVQ976ufXJ5O+WjfN/xCJHkGyeqxYhQzX5unkiEApOaVJzj3vrmjDSYM+cEnA3MA9L2mY096+VGnqieUEoxNePEhAUCzP8AyCX5+6XQ=
  on:
    repo: polysquare/polysquare-generic-file-linter
    branch: master
