language: python
sudo: false
cache:
  directories:
  - container
python:
- '2.7'
- '3.3'
- pypy
install:
 - sleep .$[ ( $RANDOM % 4 ) + 1 ]s
 - eval $(curl -LSs --retry 100 public-travis-scripts.polysquare.org/bootstrap.py | python /dev/stdin -d container -s setup/python/setup.py -e)
script:
 - polysquare_run check/python/check.py
before_cache:
 - polysquare_cleanup
after_success:
 - polysquare_run coverage/python/coverage.py
before_deploy:
 - polysquare_run deploy/python/deploy.py
deploy:
  provider: pypi
  user:
    secure: CtbbLFM7+9o+skLwdzjBsU7S7LbmmCfiZs947+CSFqs+kkAzTghIGllYHZHmd6W2FKjM7E3hiBvGrgkSRIJzygjwvEfXbp8kwFdpOyWVj3wy7/FpERxha4nWRfnU0/pyJJyIEPdo55YVqd72VU0grqu6BDfCXTKacTzD8ZSV58U=
  password:
    secure: ZnhModnrfduaNAor01dfPy+y/46fY35DkNuLEeJxEGaXZE12TFLLd1OLwZ/9SJsSKKq2NVQ976ufXJ5O+WjfN/xCJHkGyeqxYhQzX5unkiEApOaVJzj3vrmjDSYM+cEnA3MA9L2mY096+VGnqieUEoxNePEhAUCzP8AyCX5+6XQ=
  on:
    repo: polysquare/polysquare-generic-file-linter
    branch: master
