language: python
python:
- '2.7'
- '3.3'
- pypy
install:
- pip install -e .[test]
- pip install flake8 pylint coverage python-coveralls
- if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then
    pip install http://sourceforge.net/projects/pychecker/files/pychecker/0.8.19/pychecker-0.8.19.tar.gz/download;
  fi
- gem install mdl
script:
- python setup.py build
- coverage run --source=polysquarelinter setup.py test
- python setup.py install
- pylint -f colorized tests/ polysquarelinter/ --disable=r0903,R0904
- if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then
    pychecker tests/*.py polysquarelinter/*.py;
  fi
- flake8 tests/ polysquarelinter/
- mdl .
- find polysquarelinter tests setup.py -type f -name "*.py" | xargs -L 1 polysquare-generic-file-linter
after_success:
- coverage report -m
- coveralls
- rm -rf polysquare_generic_file_linter.egg-info/
- rm -rf build/
deploy:
  provider: pypi
  user:
    secure: CtbbLFM7+9o+skLwdzjBsU7S7LbmmCfiZs947+CSFqs+kkAzTghIGllYHZHmd6W2FKjM7E3hiBvGrgkSRIJzygjwvEfXbp8kwFdpOyWVj3wy7/FpERxha4nWRfnU0/pyJJyIEPdo55YVqd72VU0grqu6BDfCXTKacTzD8ZSV58U=
  password:
    secure: ZnhModnrfduaNAor01dfPy+y/46fY35DkNuLEeJxEGaXZE12TFLLd1OLwZ/9SJsSKKq2NVQ976ufXJ5O+WjfN/xCJHkGyeqxYhQzX5unkiEApOaVJzj3vrmjDSYM+cEnA3MA9L2mY096+VGnqieUEoxNePEhAUCzP8AyCX5+6XQ=
  on:
    repo: polysquare/polysquare-generic-file-linter
    branch: master
